#!/bin/sh
# postinst script
#
# see: dh_installdeb(1)

set -e

if [ -f /etc/sddm.conf ]; then
	mv /etc/sddm.conf /etc/sddm-old2.conf
fi

if [ -f /etc/sddm-sparky2.conf ]; then
	cp /etc/sddm-sparky2.conf /etc/sddm.conf
fi

exit 0


